/* eslint-disable vietnamese/vietnamese-words */

export const ACTIVITY_LABEL = {
  action_history: "Lịch sử thao tác",
  username: "Tên người dùng",
  action_time: "Thời gian",
  action_type: "Loại thao tác",
  action_name: "Chức năng",
  message: "Thông tin",
  customers: "Quản lí khách hàng",
  users: "Quản lí người dùng",
  locations: "Quản lí địa chỉ",
  products: "Quản lí sản phẩm",
  warehouses: "Quản lí kho",
  orders: "Quản lí đơn hàng",
  delivery: "Quản lí vận chuyển",
  files: "Quản lí file",
  export_file: "Xuất file",
  import_file: "Nhập file",
  detail: "Chi tiết",
  user: "Tài khoản",
  customer: "Khách hàng",
  customer_group: "Nhóm khách hàng",
  customer_group_detail: "Chi tiết nhóm khách hàng",
  order: "Đơn hàng",
  order_payment: "Thanh toán",
  department: "Phòng ban",
  address: "Địa chỉ",
  promotion_order: "Khuyến mãi đơn hàng",
  promotion_variant: "Khuyến mãi sản sản phẩm",
  promotion_voucher: "Voucher",
  product_category: "Danh mục sản phẩm",
  product: "Sản phẩm",
  product_variant_batch: "Lô",
  product_variant: "Biến thể",
  warehouse: "Kho",
  warehouse_inventory_available: "Tồn kho khả dụng",
  warehouse_sheet_check_detail: "Phiếu kiểm",

  create: "Tạo mới",
  read: "Xem",
  update: "Cập nhật",
  delete: "Xóa",
  export: "Xuất file",
  import: "Nhập file",
  login: "Đăng nhập",
  logout: "Đăng xuất",
};
