/* eslint-disable */
export const ROLE_LABEL = {
  dashboard: "Dashboard",
  update_role: "Cập nhật quyền",
  create_role: "Thêm quyền",
  cancel_order: "Huỷ đơn",
  create_delivery: "Giao hàng",
  typing_role_name_please: "Nhập tên quyền",
  select_role_please: "Vui lòng chọn quyền",
  role_name: "Tên quyền",
  default_router: "Đường dẫn mặc định",
  role_detail: "Chi tiết quyền",
  role_tab_toggle: "Mở/Đóng tất cả",
  export_excel: "Xuất Excel",
  read_and_write: "Đọc và ghi",
  read_only: "Chỉ đọc",
  account: "Tài khoản",
  inventory: "Tồn kho",
  bulk_assign_lead: "Chia số hàng loạt",
  call_center: "Trung tâm cuộc gọi",
  role: "Quyền",
  inventory_history: "Lịch sử tồn kho",
  create_update_customer: "Tạo/ cập nhật khách hàng",
  list_lead: "Danh sách Lead",
  create_assign_lead: "Tạo Lead/ Chia số",
  report_assign_lead_daily: "Báo cáo chia số hằng ngày",
  assign_lead_for_department: "Chia số cho phòng ban",
  assign_lead_for_telesales: "Chia số cho Telesales",
  telesales: "Tài khoản NV kinh doanh",
  handle_order: "Xử lý đơn",
  delivery_care: "Chăm sóc vận đơn",
  print_order: "In đơn",
  delivery: "Giao hàng",
  confirm: "Xác nhận đơn",
  payment: "Thanh toán",
  report: "Báo cáo",
  handle_delivery: "Xử lý vận đơn",
  create_update_product: "Tạo/ cập nhật sản phẩm",
  promotion: "Khuyến mãi",
  export_sheet: "Xuất kho",
  import_sheet: "Nhập kho",
  transfer_sheet: "Chuyển kho",
  check_sheet: "Kiểm kho",
  scan_order: "Quét đơn",
  scan_order_history: "Lịch sử quét đơn",
  setting: "Cấu hình",
  lead_center: "Lead Center",
  order: "Đơn hàng",
  product: "Sản phẩm",
  warehouse: "Kho",
  customer: "Khách hàng",
  assign: "Chia số",
};
