/* eslint-disable vietnamese/vietnamese-words */
export const PRODUCT_LABEL = {
  images: "Hình ảnh",
  combo_variants: "Nhóm biến thể",
  created_by: "Người tạo",
  created: "Ngày tạo",
  category_code: "Mã nhóm sản phẩm",
  modified_by: "Người xử lý",
  modified: "Ngày xử lý",
  is_active: "TT kinh doanh",
  name: "Tên sản phẩm",
  category: "Danh mục",
  width: "Chiều rộng",
  variant_SKU_code: "SKU biến thể",
  height: "Chiều cao",
  update_product_variant: "Cập nhật biến thể",
  customer: "Khách hàng",
  inventory: "Tồn kho",
  weight: "Trọng lượng",
  search_material: "Nhập SKU_code, tên, ghi chú, SKU biến thể",
  inventory_quantity: "Tồn kho",
  inventory_note: "Ghi chú tồn kho",
  combo_note: "Ghi chú Combo",
  shape_info: "Hình dáng",
  sold_quantity: "Số lượng bán ra",
  variant_sheet: "Phiếu kho",
  process: "Công đoạn",
  revenue: "Doanh thu",
  material_name: "Tên nguyên liệu",
  mass: "Trọng lượng",
  modified_info: "Thông tin chỉnh sửa",
  created_info: "Thông tin tạo",
  supplier: "Nhà cung cấp",
  total_weight: "Tổng trọng lượng",
  commission_value: "Hoa hồng",
  commission: "Hoa hồng(vnđ)",
  commission_percent: "Hoa hồng phần trăm(%)",
  product_note: "Ghi chú SP",
  variant_note: "Ghi chú biến thể",
  material_note: "Ghi chú nguyên liệu",
  error: "Lỗi",
  cross_sale_product: "Sản phẩm Crosssale",
  product_in_combo: "Sản phẩm trong combo",
  limit_gift: "Giới hạn SL tặng",
  list_variant: "Danh sách biến thể",
  file_not_have_data: "File đã chọn không tồn tại dữ liệu",
  SKU_code: "SKU sản phẩm",
  general_info: "Thông tin chung",
  see_variant: "Xem biến thể",
  price_info: "Thông tin giá",
  bar_code: "Mã vạch",
  total_inventory: "Tồn kho",
  total_material_quantity: "Số nguyên liệu",
  material: "Nguyên liệu",
  purchare_price: "Giá mua",
  neo_price: "Giá niêm yết",
  business_code: "Mã số doanh nghiệp",
  import_file: "Nhập file",
  sale_price: "Giá bán",
  total_price: "Thành tiền",
  status: "Trạng thái",
  type: "Loại",
  product: "Sản phẩm",
  variant: "Biến thể",
  quantity: "Số lượng",
  variants: "Biến thể",
  enter_name_and_sku: "Nhập tên, mã, sku sản phẩm",
  create_product: "Thêm sản phẩm",
  add_material: "Thêm nguyên liệu",
  update_product: "Cập nhật sản phẩm",
  add_variant: "Biến thể",
  update_variant: "Cập nhật biến thể",
  create_material: "Thêm nguyên liệu",
  update_material: "Cập nhật nguyên liệu",
  create_combo: "Thêm Combo",
  update_combo: "Cập nhật Combo",
  search_variant: "Nhập tên, SKU, Barcode, ghi chú, SKU sản phẩm",
  search_product: "Nhập SKU_code, tên, ghi chú",
  select_category: "Chọn danh mục sản phẩm",
  create_category: "Thêm danh mục sản phẩm",
  update_category: "Cập nhật danh mục sản phẩm",
  create_supplier: "Thêm nhà cung cấp",
  select_supplier: "Chọn nhà cung cấp",
  update_supplier: "Cập nhật nhà cung cấp",
  add_attribute: "Thêm mới thuộc tính",
  update_attribute: "Cập nhật thuộc tính",
  combo: "Compo sản phẩm",
  price_with_discount: "Giá KM",
  combo_name: "Tên combo",
  discount: "Giảm giá",
  input_combo: "Nhập tên combo",
  select_product: "Chọn sản phẩm",
  select_variant: "Vui lòng chọn sản phẩm",
  select_combo_variant: "Chọn biến thể cho combo",
  create_product_variant: "Tạo biến thể cho sản phẩm",
  create_variant_des:
    "Thêm các biến thể khi sản phẩm có các phiên bản khác nhau, chẳng hạn như màu sắc và kích thước",
  input_SKU: "Nhập SKU",
  input_bar_code: "Nhập mã vạch",
  input_note: "Nhập ghi chú",
  input_name: "Nhập tên sản phẩm",
  no_data_panel: "Trên là 1 biến thể",
  variant_name: "Tên biến thể",
  import_export_history: "Lịch sử nhập xuất",
  product_details: "Chi tiết sản phẩm",
  error_get_product: "Không lấy được thông tin sản phẩm",
  total_inventory_from: "Tồn kho từ",
  total_inventory_to: "Tồn kho tới",
  total_variants: "Tổng biến thể",
  quantity_non_confirm: "Số lượng đã lên đơn chưa xác nhận",
  quantity_confirm: "Số lượng đã lên đơn đã xác nhận",
  batch: "Lô",
  batche_list: "Danh sách lô",
  tags: "Danh sách thẻ",
  active: "Đang kinh doanh",
  inactive: "Ngừng kinh doanh",
  list_material: "Danh sách nguyên liệu",
  list_product: "Danh sách sản phẩm",
  "all-product": "Tất cả sản phẩm",
  "all-variant": "Tất cả biến thể",
  "simple-product": "Sản phẩm",
  "simple-variant": "Biến thể",
  simple: "Đơn",
  cannot_select_over_limit_option: "Không thể chọn quá giới hạn lựa chọn",
  not_limit: "Không giới hạn",
};
