/* eslint-disable vietnamese/vietnamese-words */
export const PIVOT_LABEL = {
  order_info: "Đơn hàng",
  status: " Trạng thái đơn hàng",
  general_info: "Thông tin chung",
  handle_info: "Thông tin xử lý",
  create_info: "Thông tin tạo",
  customer: "Tên khách hàng",
  price_info: "Thanh toán",
  payments: "Trạng thái thanh toán",
  shipping_info: "Thông tin vận chuyển",
  cancel_reason: "Lý do huỷ đơn",
  print_info: "Thông tin in đơn",
  third_party_id: "ID bên thứ 3",
  third_party_name: "Tên bên thứ 3",
  third_party_type: "Loại bên thứ 3",
  history_date: "Thời gian chỉnh sửa",
  modified_by: "Người chỉnh sửa",
  history_type: "Loại thao tác",
  require_dimension_metric: "Vui lòng chọn đối tượng và số liệu",
  show_date: "Thời gian show dữ liệu",
  show_chart: "Hiện biểu đồ",
  time: "Thời gian",
  compare: "So sánh",
  range_date: "Phạm vi thời gian",
  dimension: "Đối tượng",
  dimension_filter: "Bộ lọc đối tượng",
  metric: "Số liệu hiển thị",
  metric_filter: "Bộ lọc số liệu",
  add_or_search: "Thêm hoặc tìm kiếm",
  search: "Tìm kiếm",
  enter_value: "Nhập giá trị",
  enter_min_value: "Nhập giá trị min",
  enter_max_value: "Nhập giá trị max",
  add_filter: "Thêm điều kiện lọc",
};
