/* eslint-disable vietnamese/vietnamese-words */
export const CUSTOMER_LABEL = {
  name: "Tên",
  customer_note: "Ghi chú KH",
  email: "Email",
  birthday: "Sinh nhật",
  groups: "Nhóm",
  gender: "Giới tính",
  customer: "Khách hàng",
  addresses: "Địa chỉ",
  success_order_revenue: "Doanh thu đơn thành công",
  source: "Nguồn",
  general_info: "Thông tin chung",
  tags: "Thẻ",
  birthday_day: "Ngày sinh",
  birthday_month: "Tháng sinh",
  created_from: "Ngày tạo từ",
  created_to: "Ngày tạo tới",
  birthday_from: "Sinh nhật từ",
  birthday_to: "Sinh nhật tới",
  not_found_customer: "Không tìm thấy khách hàng",
  info: "Thông tin khách hàng",
  order_status: "Trạng thái đơn",
  rank: "Hạng khách hàng",
  last_order_time: "Lần giao dịch cuối",
  last_order_time_from: "Giao dịch cuối từ",
  last_order_time_to: "Giao dịch cuối tới",
  phones: "Số điện thoại",
  phone_number: "Số điện thoại",
  shipping_address: "Địa chỉ giao hàng",
  call_center: "Cuộc gọi",
  created_by: "Người tạo",
  created: "Ngày tạo",
  order_info: "Thông tin mua hàng",
  new: "Mới",
  province: "Tỉnh/ thành",
  order_success_count: "Số đơn thành công",
  district: "Quận/ huyện",
  add_telesale: "Thêm nhân viên kinh doanh",
  account: "Nhân sự",
  ward: "Phường/ xã",
  carrier: "Người chăm sóc",
  old: "Cũ",
  modified_by: "Người xử lý",
  modified: "Ngày xử lý",
  history_change_reason: "Lý do cập nhật",
  spent_from: "Chi tiêu từ",
  spent_to: "Chi tiêu tới",
  total_spent: "Tổng chi tiêu",
  total_order: "Tổng đơn hàng",
  latest_up_rank_date: "Ngày nâng hạng",
  customer_care_staff: "Người chăm sóc",
  ecommerce_id: "Mã TMĐT",
  modified_care_staff_by: "Người thay đổi nhân viên chăm sóc",
  shipping_return_order: "Số ĐH hoàn trả vận chuyển",
  shipping_return_spent: "Doanh thu ĐH hoàn trả",
  shipping_cancel_order: "Số ĐH hủy vận chuyển",
  shipping_cancel_spent: "Doanh thu ĐH hủy",
  update_customer: "Cập nhật khách hàng",
  create_customer: "Thêm khách hàng",
  history_type: "Loại thao tác",
  search_placeholder: "Nhập sđt, tên, email khách hàng",
  lead_history: "Lịch sử tạo LEAD",
  lead_center: "Lead Center",
  orders_tab_label: "Đơn hàng & Sản phẩm",
  create_lead: "Tạo lead",
  order: "Đơn hàng",
  create_order: "Tạo đơn hàng",
  delivery: "Vận đơn",
  create_delivery: "Tạo vận đơn",
  input_phone: "Nhập số điện thoại",
  select_tags: "Chọn thẻ",
  customer_info: "Thông tin khách hàng",
  set_default_address: "Đặt làm mặc định",
  select_default_address: "Chọn địa chỉ mặc định",
  delete_address: "Xóa địa chỉ",
  add_phone: "Thêm số điện thoại",
  delete_phone: "Xóa số điện thoại",
  error_no_data: "Không có thông tin khách hàng",
  success_update_address: "Đã thay đổi địa chỉ mặc định",
  address_not_available: "Không có địa chỉ",
  male: "Nam",
  female: "Nữ",
  silver: "Bạc",
  gold: "Vàng",
  diamond: "Kim cương",
  vip: "VIP",
  list_customer: "Danh sách khách hàng",
};
