/* eslint-disable vietnamese/vietnamese-words */
export const BUTTON = {
  ADD: "Thêm",
  UPDATE: "Cập nhật",
  EDIT: "Chỉnh sửa",
  SELECT: "Chọn",
  CLOSE: "Đóng",
  ADD_ADDRESS: "Thêm địa chỉ",
  RE_ORDER: "Đặt lại",
  DUPLICATE: "Nhân đôi",
  ACCEPT: "Xác nhận",
  GO_BACK: "Quay lại",
  SAVE: "Lưu",
  CANCEL: "Huỷ",
  CANCEL_ORDER: "Huỷ đơn",
  CREATE_VARIANT: "Tạo biến thể",
  APPLY: "Áp dụng",
  CREATE_MATERIAL: "Tạo nguyên liệu",
  CANCEL_SHEET: "Huỷ phiếu",
  CONFIRM: "Xác nhận",
  DELETE: "Xoá",
  HANDLE: "Xử lý",
  DETAIL: "Chi tiết",
  VISIBLE_COLUMNS: "Lọc cột",
  ADD_PRODUCT: "Thêm sản phẩm",
  NEXT: "Tiếp theo",
  DELIVERY: "Giao hàng",
  RENAME: "Đổi tên",
  UPDATE_CUSTOMER: "Cập nhật thông tin khách",
  HANDLE_SHIPPING: "Xử lý mã vận đơn",
  CANCLE_SHIPPING: "Huỷ vận đơn",
  CREATE_SHIPPING: "Tạo vận đơn",
  CREATE_PROMOTION: "Tạo khuyến mãi",
  CREATE_ORDER: "Tạo đơn",
  PRINT: "In",
  IMPORT: "Nhập",
  EXPORT: "Xuất",
  CREATE_PRODUCT: "Tạo sản phẩm",
  CREATE_COMBO: "Tạo combo",
  SCAN_CODE: "Quét mã",
  START_SCAN_CODE: "Bắt đầu quét",
};
