/* eslint-disable vietnamese/vietnamese-words */
export const LABEL = {
  DASHBOARD: "Dashboard",
  COPIED: "Đã copy",
  ADD_15_MINUTES: "Thêm 15 phút",
  MODIFIED: "Thời gian XL",
  NAME: "Tên",
  GROWING: "Đang phát triển...",
  NONE: "Chưa có",
  COMPLETED: "Hoàn thành",
  GO_TO_PAGE: "Đến trang",
  GO_BACK: "Quay lại",
  SELECT_DATE: "Chọn ngày",
  SELECT_CORRECT_PLEASE: "Vui lòng chọn đúng",
  ROW_PER_PAGE: "Số dòng/ trang",
  SHOW_FULL_DATA: "Đã lấy toàn bộ dữ liệu",
  DETAIL: "Chi tiết",
  ALL: "Tất cả",
  MAXIMUM: "Tối đa",
  ACS: "Tăng dần",
  SERVER_ERROR: "Lỗi hệ thống!",
  SERVER_ERROR_DESCRIPTION:
    "Xin lỗi vì sự cố lỗi hệ thống, vui lòng liên hệ người quản lý hệ thống hoặc nhấn vào nút trang chủ để làm mới trang",
  CLOSE: "Đóng",
  DESC: "Giảm dần",
  FILTER: "Bộ lọc",
  SORT: "Sắp xếp",
  LOGOUT: "Đăng xuất",
  WELCOME: "Xin chào",
  SEE: "Xem",
  COMBO: "Combo",
  PEOPLE: "Người",
  LOGGED_IN: "Đã đăng nhập",
  NOT_LOGIN: "Chưa đăng nhập",
  SENT: "Gởi",
  ACCEPT: "Cho phép",
  ACTION: "Thao tác",
  IMAGE_USED_TO_PREVIEW: "Hình ảnh được sử dụng để trình chiếu",
  DEFAULT: "Mặc định",
  SELECT_IMAGE: "Chọn ảnh",
  NOT_PROTECTED: "Không có quyền!",
  CONTACT_ADMIN: "Bạn không có quyền truy cập vào trang. Vui lòng liên hệ Admin.",
  CONTINUE: "Tiếp tục",
  ORDER_OF_OBJECT_APPEARANCE: "Thứ tự xuất hiện đối tượng",
  DRAG_AND_DROP_IMAGE: "Kéo thả hoặc chọn tải lên hình ảnh",
  ORDER_OF_DATA: "Thứ tự số liệu hiển thị",
  SIZE_OF_FILE_LESS_THAN_2MB: "File có dung lượng nhỏ hơn 2MB",
  SETTING: "Cài đặt",
  OTHER: "Khác",
  DATE: "Ngày",
  MODIFIED_BY: "Người XL",
  TOGGLE_SELECT: "Chọn / Bỏ chọn tất cả",
  CREATED_BY: "Người tạo",
  CREATED_FROM: "Ngày tạo từ",
  CREATED_TO: "Ngày tạo tới",
  ADD_ADDRESS: "Thêm địa chỉ",
  ADD_PHONE_NUMBER: "Thêm số điện thoại",
  REASON: "Lý do",
  STATUS: "Trạng thái",
  NOTE: "Ghi chú",
  IMPORT_FILE: "Nhập File",
  SELECT_COLUMN_VALUE: "Chọn giá trị cột",
  EDIT_CELL: "Chỉnh sửa ô",
  NO_DATA: "Không có dữ liệu",
  LOADING_DATA: "Đang tải dữ liệu...",
  HISTORY_USER: "Người cập nhật",
  RETURN_LIST: "Quay về danh sách",
  OPTION_DATE: "Ngày tuỳ chọn",
  SELECT_HEIGHT_DATE: "Vui lòng chọn lớn hơn ngày bắt đầu",
  FROM: "Từ",
  TO: "Đến",
  WEEK: "Tuần",
  MONTH: "Tháng",
  QUARTER: "Quý",
  YEAR: "Năm",
  CHART: "Biểu đồ",
  ARE_YOU_SURE_DELETE: "Bạn chắc chắn muốn xóa?",
  NO: "Không",
  HIDDEN_FILTER: "Ẩn bộ lọc",
  SHOW_FILTER: "Xem bộ lọc",
  SELECT: "Chọn",
  MULTI_SELECT: "Chọn nhiều",
  HISTORY_CHANGE_REASON: "Lý do cập nhật",
  HISTORY_TYPE: "Loại cập nhật",
  EXPORT: "Xuất file",
  TAG: "Thẻ",
  EXPORT_EXCEL_TO_GMAIL: "Xuất đến Email",
  DEFAULT_DATE: "Ngày mặc định",
  CLEAR_FILTER: "Xoá bộ lọc",
  CREATED: "Thời gian tạo",
  SET_DEFAULT: "Đặt làm mặc định",
  TIME: "Thời gian",
  SEARCH: "Tìm kiếm",
  ATTRIBUTE: "Thuộc tính",
  HELPCENTER: "Trung tâm trợ giúp",
  PRODUCT_TAG: "Thẻ sản phầm",
  CATEGORY: "Nhóm sản phẩm",
  SEE_MORE: "Xem thêm",
  EXPEND: "Rút gọn",
  CATEGORY_CODE: "Mã nhóm",
  SUPPILER: "Nhà cung cấp",
  BUSINESS_CODE: "Mã số doanh nghiệp",
  CUSTOMER_TAG: "Thẻ khách hàng",
  CUSTOMER_GROUP: "Nhóm khách hàng",
  CLICK_CELL_TO_EDIT: "*Click vào ô trong bảng để chỉnh sửa",
  IMPORT_FILE_DESCRIPTION: "Format cột trước khi nạp dữ liệu",
  IMPORT_FILE_TEMPLATE: "File mẫu",
  PERCENT: "Phần trăm",
  PRICE_AMOUNT: "Số tiền",
  HISTORY: "Lịch sử",
  ACTIVE: "Kích hoạt",
  CLICK_TO_UPDATE: "Click để cập nhật",
  URL: "Đường dẫn",
  INPUT: "Nhập",
  TOTAL: "Tổng",
  PASSWORD: "Mật khẩu",
  LOGIN: "Đăng nhập",
  LOGIN_TO_SKYCOM: "Đăng nhập vào Skycom",
  NOT_FOUND: "Không tìm thấy!",
  NOT_FOUND_PAGE_URL: "Xin lỗi vì không tìm thấy trang nào liên quan đến URL bạn vừa truy cập",
  HOME: "Trang chủ",
  CANNOT_LOGOUT: "Không thể đăng xuất",
  NOT_FOUND_ERROR: "Lỗi không xác định",
  DOUBLE_CLICK_TO_ADD_VALUE: "Double click để thêm giá trị",
  CLICK_TO_ADD_VALUE: "Click để thêm giá trị",
  DEACTIVE: "Ngưng hoạt động",
  CONFIRMED: "Đã xác nhận",
  NO_CONFIRMED: "Chưa xác nhận",
  ERROR_CONNECT_DATA: "Lỗi kết nối dữ liệu",
  TODAY: "Hôm nay",
  YESTERDAY: "Hôm qua",
  THREE_DAYS_AGO: "3 ngày trước",
  SEVEN_DAYS_AGO: "7 ngày trước",
  FOURTEEN_DAYS_AGO: "14 ngày trước",
  THIRTY_DAYS_AGO: "30 ngày trước",
  NINETY_DAYS_AGO: "90 ngày trước",
  THREE_DAYS_AGO_AND_TODAY: "3 ngày trước và hôm nay",
  SEVEN_DAYS_AGO_AND_TODAY: "7 ngày trước và hôm nay",
  FOURTEEN_DAYS_AGO_AND_TODAY: "14 ngày trước và hôm nay",
  THIRTY_DAYS_AGO_AND_TODAY: "30 ngày trước và hôm nay",
  NINETY_DAYS_AGO_AND_TODAY: "90 ngày trước và hôm nay",
  LAST_MONTH: "Tháng trước",
  THIS_MONTH: "Tháng này",
  CUSTOM: "Tuỳ chọn",
  JANUARY: "Tháng 1",
  FEBRUARY: "Tháng 2",
  MARCH: "Tháng 3",
  APRIL: "Tháng 4",
  MAY: "Tháng 5",
  JUNE: "Tháng 6",
  JULY: "Tháng 7",
  AUGUST: "Tháng 8",
  SEPTEMPER: "Tháng 9",
  OCTOBER: "Tháng 10",
  NOVEMBER: "Tháng 11",
  DECEMBER: "Tháng 12",
  REPORT: "Báo cáo",
  PROFILE: "Thông tin các nhân",
  TERM_OF_SERVICE: "Điều khoản sử dụng",
  CURRENCY_UNIT: "0 đ",
  PRIVACY: "Chính sách",
  CONFIRMED_REMOVE: "Bạn chắc chắn muốn xóa?",
  TOMORROW: "Tomorrow",
  ONE_WEEK_AGO: "Tuần trước",
  ONE_WEEK_FROM_NOW: "7 ngày trước",
  ONE_MONTH_AGO: "Tháng trước",
  ONE_MONTH_FROM_NOW: "30 ngày trước",
  NUMBER_OF_DAYS_AGO: "số ngày trước",
  NUMBER_OF_DAYS_FROM_NOW: "Number of days from now",
  EXACT_DATE: "Chọn 1 ngày trong lịch",
  THE_PAST_WEEK: "Tuần qua",
  THE_PAST_MONTH: "Tháng qua",
  THE_PAST_YEAR: "Năm qua",
  THE_NEXT_WEEK: "The Next Week",
  THE_NEXT_MONTH: "The Next Month",
  THE_NEXT_YEAR: "The Next Year",
  THE_NEXT_NUMBER_OF_DAYS: "The Next Number Of Days",
  THE_PAST_NUMBER_OF_DAYS: "Số ngày qua",
  IS_BETWEEN: "Giữa",
  IS_EXCEPT: "Ngoại trừ",
  IS_EMPTY: "Rỗng",
  IS_NOT_EMPTY: "Không rỗng",
  CONTAINS: "Chứa",
  DOES_NOT_CONSTAINS: "Không chứa",
  IS: "Là",
  IS_NOT: "is not",
  IS_ANY_OF: "Bất kì trong số",
  IS_NONE_OF: "Không có gì trong số",
  IS_EXACTLY: "Chinh xác",
  HAS_ANY_OF: "Có bất kỳ trong",
  HAS_ALL_OF: "Có tất cả của",
  HAS_NONE_OF: "Không có nào trong",
  IS_BEFORE: "Trước",
  IS_AFTER: "Sau",
  IS_ON_OR_BEFORE: "Hiện tại và trước đó",
  IS_ON_OR_AFTER: "Hiện tại và sau đó",
  IS_WITHIN: "Trong vòng",
};
