#!/bin/sh
#ecommerce
echo CI_REGISTRY=$CI_REGISTRY  >> .env
echo DEBUG=0 >> .env
echo IMAGE=$IMAGE >> .env
echo REACT_APP_NGINX_IMAGE=$IMAGE:nginx  >> .env

echo REACT_APP_API_URL=$REACT_APP_API_URL_KMV >> .env
echo REACT_APP_REPORT_API=$REACT_APP_API_REPORT_KMV >> .env

echo REACT_APP_CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA >> .env
echo REACT_APP_CI_COMMIT_TIMESTAMP=$CI_COMMIT_TIMESTAMP >> .env

echo REACT_APP_SENTRY_URL=$REACT_APP_SENTRY_URL >> .env