#!/bin/sh
echo DEBUG=0 >> .env
echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env
echo CI_REGISTRY_USER=$CI_REGISTRY_USER   >> .env
echo CI_REGISTRY=$CI_REGISTRY  >> .env
echo REACT_APP_CI_COMMIT_TIMESTAMP=$CI_COMMIT_TIMESTAMP >> .env
echo REACT_APP_CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA >> .env

echo REACT_APP_SENTRY_URL=$REACT_APP_SENTRY_URL >> .env

echo IMAGE=$IMAGE >> .env
echo REACT_APP_NGINX_IMAGE=$IMAGE:nginx  >> .env

echo REACT_APP_API_URL=$REACT_APP_API_URL_TAM >> .env
echo REACT_APP_REPORT_API=$REACT_APP_API_REPORT_TAM >> .env
