/* eslint-disable vietnamese/vietnamese-words */
export const WAREHOUSE_LABEL = {
  created_by: "Người tạo",
  created: "Ngày tạo",
  modified_by: "Người xử lý",
  batch_quantity: "Lô - Số lượng",
  batch_system_quantity: "Lô - Số lượng hệ thống",
  actual_quantity: "Số lượng thực thế",
  select_sheet_type_please: "Vui lòng chọn loại phiếu kho",
  difference_quantity: "Chênh lệch",
  import_quantity: "Số lượng nhập",
  export_quantity: "Số lượng xuất",
  transfer_quantity: "Số lượng chuyển",
  quantity_column_helper_label: "Cột số lượng là số lượng",
  checked_quantity: "Số lượng kiểm",
  report_inventory_by_category: "Báo cáo tồn kho theo danh mục",
  modified: "Ngày xử lý",
  is_default: "Kho mặc định",
  name: "Tên kho",
  category: "Danh mục",
  search_warehouse: "Nhập mã, ghi chú, SKU biến thể, tên biến thể, tên lô",
  warehouse_note: "Ghi chú kho",
  date: "Thời gian",
  manager_name: "Tên NQL",
  manager_phone: "Số điện thoại NQL",
  order_key: "Mã đơn",
  enter_order_key: "Nhập mã đơn",
  is_sales: "Kho bán hàng",
  address: "Địa chỉ",
  sheet_code: "Mã phiếu",
  enter_sheet_code: "Nhập mã phiếu",
  confirmed_date: "Ngày xác nhận",
  manager_info: "Thông tin quản lý",
  confirmed_date_from: "Ngày XN từ",
  confirmed_date_to: "Ngày XN tới",
  modified_info: "Thông tin xử lý",
  addresses: "Địa chỉ",
  status: "Trạng thái",
  search: "Nhập kho",
  search_batches: "Nhập tên lô",
  shipping_phone_number: "Số điện thoại để bên giao hàng gọi",
  address_default: "Chọn địa chỉ mặc định",
  delete_address: "Xoá địa chỉ",
  select_province: "Chọn tỉnh/ thành",
  select_district: "Chọn quận/huyện",
  select_ward: "Chọn phường/ xã",
  address_address: "Số nhà, đường",
  warehouse_details: "Chi tiết kho",
  warehouse: "Kho",
  list_warehouse: "Danh sách kho",
  all: "Tất cả kho",
  "inventory-history": "Lịch sử tồn kho",
  warehouse_import: "Nhập kho",
  warehouse_export: "Xuất kho",
  warehouse_transfer: "Chuyển kho",
  warehouse_checked: "Kiểm kho",
  select_warehouse_please: "Vui lòng chọn kho",
  select_warehouse_manager: "Vui lòng nhập tên người quản lí kho",
};

export const SHEET_LABEL = {
  select_batch: "Chọn lô",
  quantity_system: "Số lượng hệ thống",
  quantity_actual: "Số lượng thực tế",
  create_batch: "Thêm lô",
  code: "Mã phiếu",
  sheet_note: "Ghi chú phiếu",
  category: "Danh mục",
  order_key: "Đơn hàng",
  include_symbol: "Bao gồm cả dấu #",
  search_sheet: "Nhập mã phiếu, ghi chú, tên biến thể, SKU biến thể, tên lô",
  list_sheet: "Danh sách phiếu kho",
  cancelled: "Đã huỷ",
  inventory: "Tồn kho",
  status: "Trạng thái",
  variant: "Biến thể",
  not_cancel: "Chưa huỷ",
  batch: "Lô",
  sheet: "Phiếu kho",
  created_info: "Thông tin tạo",
  product: "Sản phẩm",
  quantity: "Số lượng",
  type: "Loại phiếu",
  created_by: "Người tạo phiếu",
  created: "Ngày tạo phiếu",
  modified_by: "Người chỉnh sửa",
  modified: "Ngày cập nhật phiếu",
  is_delete: "Đã xóa",
  is_confirm: "Trạng thái",
  confirm: "Xác nhận",
  confirm_info: "Thông tin xác nhận",
  modified_info: "Thông tin xử lý",
  confirm_date: "Ngày xác nhận",
  confirm_by: "Người xác nhận",
  note: "Ghi chú phiếu kho",
  order: "Đơn hàng",
  warehouse: "Kho",
  warehouse_from: "Kho nguồn",
  warehouse_to: "Kho đích",
  change_reason: "Lý do",
  search: "Nhập mã phiếu, mã đơn hàng",
  confirm_sheet_success: "Xác nhận phiếu thành công",
  confirm_sheet_error: "Xác nhận phiếu thất bại",
  select_product: "Vui lòng chọn sản phẩm",
  error_get_sheet_info: "Không lấy được thông tin Phiếu",
  sheet_details: "Chi tiết phiếu",
  confirmed: "Đã xác nhận",
  not_confirm: "Chưa xác nhận",
  import: "Phiếu nhập",
  export: "Phiếu xuất",
  transfer: "Phiếu chuyển",
  checked: "Phiếu kiểm",
  scan: "Quét đơn",
  IP: "Phiếu nhập",
  EP: "Phiếu xuất",
  TF: "Phiếu chuyển",
  CK: "Phiếu kiểm",
  "scan-history": "Lịch sử quét",
  import_warehouse: "Kho nhập",
  export_warehouse: "Kho xuất",
  from_warehouse: "Kho nguồn",
  transfer_warehouse: "Kho chuyển",
  checked_warehouse: "Kho kiểm",
  import_warehouse_reason: "Lý do kho nhập",
  export_warehouse_reason: "Lý do kho xuất",
  transfer_warehouse_reason: "Lý do kho chuyển",
  checked_warehouse_reason: "Lý do kho kiểm",
  actual: "Thực tế",
  select_reason_please: "Vui lòng chọn lý do",
  select_batch_please: "Vui lòng chọn lô",
  select_quantity_please: "Vui lòng nhập số lượng",
  select_export_warehouse_please: "Vui lòng chọn kho đi",
  select_import_warehouse_please: "Vui lòng chọn kho đến",
};

export const INVENTORY_LOG_LABEL = {
  search: "Nhập tên sản phẩm, mã phiếu kho",
  created_by: "Người tạo",
  created: "Ngày tạo",
  modified_by: "Người cập nhật",
  modified: "Ngày cập nhật",
  product: "Sản phẩm",
  total_inventory: "Tổng tồn kho",
  variant: "Biến thể",
  sale_price: "Giá bán biến thể",
  batch: "Lô",
  confirmed: "Đã xác nhận",
  not_confirm: "Chưa xác nhận",
  quantity: "Số lượng",
  image: "Hình ảnh",
  type: "Loại phiếu",
  variant_SKU_code: "Biến thể SKU",
  sheet_status: "Trạng thái",
  sheet_code: "Mã phiếu",
  sheet_type: "Loại phiếu",
  product_variant: "Biến thể",
  product_variant_batch: "Lô",
  warehouse: "Kho",
  change_reason: "Lý do chuyển kho",
  SKU: "SKU biến thể",
  sheet_note: "Ghi chú phiếu",
  confirm_date: "Ngày xác nhận",
  confirm_by: "Người xác nhận",
  inventory: "Tồn kho",
  quantity_system: "Số lượng tồn",
  quantity_actual: "Số lượng thực",
  create_by: "Người tạo phiếu",
  variant_batch_id: "Sản phẩm",
  batch_name: "Tên lô",
  first_inventory: "Tồn kho đầu",
  c_import: "SL nhập",
  c_export: "SL xuất",
  last_inventory: "Tồn kho cuối",
  warehouse_name: "Tên kho",
  // product inventory
  product_name: "Tên sản phẩm",
  product_SKU_code: "SKU",
  product_first_inventory: "Tồn kho đầu",
  product_c_import: "Số lượng nhập",
  product_c_export: "Số lượng xuất",
  product_last_inventory: "Tồn kho cuối",
  category_name: "Danh mục",
  // variant inventory
  variant_name: "Tên biến thể",
  variant_first_inventory: "Tồn kho đầu",
  variant_c_import: "Số lượng nhập",
  variant_c_export: "Số lượng xuất",
  variant_last_inventory: "Tồn kho cuối",
};

export const SCAN_CODE_LABEL = {
  all_code: "Tổng mã phiếu",
  confirmed: "Đã xác nhận",
  error: "Lỗi",
  duplicate: "Trùng",
  stt: "STT",
  code: "MÃ PHIẾU",
  result: "KẾT QUẢ",
  no_data: "Danh sách phiếu trống",
  scan_at: "Thời gian quét",
  scan_by: "Người quét",
  turn_number: "Lần quét",
  count: "Tổng số phiếu",
  search: "Nhập người quét",
  type: "Loại phiếu",
  status: "Trạng thái",
  order_key: "Mã quét",
  message: "Ghi chú quét đơn",
  scan_info: "Thông tin quét",
};
