/* eslint-disable vietnamese/vietnamese-words */

export const DASHBOARD_LABEL = {
  images: "Hình ảnh",
  total_order: "Tổng đơn hàng",
  total_order_completed: "Tổng đơn hoàn thành",
  total_price_actual: "Doanh thu",
  total_price_actual_completed: "Doanh thu đơn hoàn thành",
  customer_return_rate: "Tỷ lệ khách quay lại (%)",
  total_price_avg: "Doanh thu/ đơn",
  new_customer_total: "Số lượng khách hàng mới",
  lead_qualified: "Tổng Lead chất lượng",
  purchase_rate: "Tỷ lệ mua hàng (%)",
  compare_prev_month: "So với tháng trước",
  by_pre_month: "So với tháng trước",
  total_order_today: "Đơn hàng hôm nay",
  total_price_actual_today: "Doanh thu hôm nay",
  total_price_actual_current_month: "Doanh thu tháng này",
  total_order_current_month: "Đơn hàng tháng này",
  conversion_rate: "Tỷ lệ chuyển đổi (%)",
  total_lead: "Tổng Lead",
  total_lead_assigned: "Tổng Lead được chia",
  lead_buy: "Lead có mua",
  top_product_by_revenue: "Top sản phẩm bán chạy",
  top_telesale_by_revenue: "Top người bán hàng theo doanh thu",
  modified_by: "Người chỉnh sửa",
  sale_name: "Tên Telesale",
  total_revenue: "Tổng doanh thu",
  SKU_code: "SKU",
  total_price: "Tổng doanh thu",
  total_quantity: "Tổng số lượng",
  variant_name: "Tên sản phẩm",
  variant_type: "Loại sản phẩm",
  revenue_by_source: "Doanh thu theo kênh bán hàng",
  chart_revenue_by_source: "Đồ thị",
  total_cross_sale: "Doanh thu Cross Sale",
  total_revenue_crm: "Doanh thu CRM",
  source_name: "Kênh bán hàng",
  paid: "Số tiền thanh toán đã XN",
  price_pre_paid: "Số tiền trả trước",
  price_total_order_actual: "Doanh thu thực",
  price_total_variant_all: "Doanh thu từ sản phẩm",
};
