/* eslint-disable  */
export const USER_LABEL = {
  user: "Nhân sự",
  name: "Tên",
  email: "Email",
  phone: "Số điện thoại",
  is_active: "Tài khoản hoạt động",
  is_superuser: "Super user",
  is_online: "Online",
  is_CRM: "CMR",
  default_router: "Đường dẫn mặc định",
  is_hotdata: "Dữ liệu nóng",
  role: "Quyền",
  created_by: "Người tạo",
  invite_date: "Thời gian mời",
  payment: "Thanh toán",
  search_customer: "Tìm kiếm khách hàng",
  is_assign_lead_campaign: "Chạy chiến dịch",
  total_order: "Tổng đơn hàng",
  total_revenue: "Tổng doanh thu",
  total_commission: "Tổng hoa hồng",
  total_revenue_crm: "Tổng đơn hàng",
  created_at: "Thời gian tạo",
  created_from: "Thời gian tạo từ",
  invite_code: "Mã mời",
  created_to: "Thời gian tạo tới",
  created: "Thời gian tạo",
  enter_invite_code_by: "Tên người nhập mã",
  invite_count: "Lượt mời",
  invite_url: "Đường dẫn mời",
  report: "Báo cáo",
  reward: "Phần thưởng",
  invite: "Mời bạn có thưởng",
  image: "Hình ảnh",
  modified_by: "Người xử lý",
  telesale_status_tooltip: "Khi tắt online thì không thể tự động chia số",
  search_placeholder: "Nhập tên nhân sự",
  role_tab: "Theo quyền",
  feature_tab: "Theo tính năng",
  active: "Hoạt động",
  inactive: "Không hoạt động",
  upload_image_success: "Upload hình ảnh thành công",
  update_account_success: "Cập nhật tài khoản thành công",
  upload_account_error: "Cập nhật tài khoản thất bại",
  enter_new_password: "Nhập mật khẩu mới",
  new_password: "Mật khẩu mới",
  re_enter_new_password: "Nhập lại mật khẩu",
  confirm_password: "Xác nhận mật khẩu",
  change_password: "Thay đổi mật khẩu",
  account_info: "Thông tin tài khoản",
  status: "Trạng thái",
  select_role_please: "Vui lòng chọn quyền",
  select_permission_please: "Vui lòng nhập tên quyền",
  enter_name: "Nhập tên",
  enter_email: "Nhập email",
  enter_phone: "Nhập số điện thoại",
  enter_password: "Nhập mật khẩu",
  select_role: "Chọn quyền",
  password: "Mật khẩu",
  department: "Phòng ban",
  select_department: "Chọn phòng ban",
  select_department_please: "Vui lòng chọn phòng ban",
};
